[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.zip", "php82Extensions.bcmath", "php82Extensions.gd"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

